// Realistic sample data for local development and testing. Never run against production.

export const DEMO_PASSWORD = "passalong-demo-pass"; // test-only password for all seeded accounts

export const SAMPLE_USERS = [
  { name: "Admin", username: "pa_admin", email: "admin@passalong.test", role: "admin", location: "London" },
  { name: "Mo Moderator", username: "pa_moderator", email: "moderator@passalong.test", role: "moderator", location: "Leeds" },
  { name: "Amelia Hart", username: "amelia_wardrobe", email: "amelia@passalong.test", location: "Bristol", bio: "Mostly size 10. Smoke-free, pet-free home. I post Mon/Wed/Fri." },
  { name: "Raj Patel", username: "rajsneakers", email: "raj@passalong.test", location: "Leicester", bio: "Trainer collector clearing space. All pairs authentic – receipts where I have them." },
  { name: "Siobhan Kelly", username: "shiv_vintage", email: "siobhan@passalong.test", location: "Belfast", bio: "Vintage finds and charity-shop treasures. Bundle for discounts!" },
  { name: "Tom Fletcher", username: "tomf", email: "tom@passalong.test", location: "Manchester", bio: "Dad of two – outgrown kids' stuff, all good condition." },
  { name: "Grace Owusu", username: "graceful_closet", email: "grace@passalong.test", location: "London", bio: "Minimalist wardrobe edit. Sizes 12–14." },
  { name: "Callum Reid", username: "callum_reads", email: "callum@passalong.test", location: "Edinburgh", bio: "Books, records and games. Fast dispatch." },
  { name: "Hannah Lewis", username: "hannahlew", email: "hannah@passalong.test", location: "Cardiff", bio: "Homeware lover. Collection possible in Cardiff." },
  { name: "Ollie Brooks", username: "olliebrooks", email: "ollie@passalong.test", location: "Brighton", bio: "Outdoor kit and menswear." },
  { name: "Priya Shah", username: "priya_buys", email: "priya@passalong.test", location: "Birmingham", bio: "Mainly here to buy!" },
  { name: "Ben Carter", username: "bencarter", email: "ben@passalong.test", location: "Newcastle", bio: "Dog dad. Selling bits our pup never used." },
] as const;

type Cond = "NEW_WITH_TAGS" | "NEW_WITHOUT_TAGS" | "VERY_GOOD" | "GOOD" | "SATISFACTORY";

export type SampleListing = {
  seller: string;
  title: string;
  description: string;
  category: string; // category path
  brand?: string;
  size?: string;
  condition: Cond;
  colours: string[];
  material?: string;
  pricePence: number;
  parcel: "SMALL" | "MEDIUM" | "LARGE";
};

export const SAMPLE_LISTINGS: SampleListing[] = [
  { seller: "amelia_wardrobe", title: "Zara floral midi dress", description: "Green floral midi with puff sleeves. Worn twice to weddings, no marks or bobbling. Fully lined.", category: "women/clothing/dresses", brand: "Zara", size: "UK 10 / S", condition: "VERY_GOOD", colours: ["Green"], material: "Viscose", pricePence: 1800, parcel: "SMALL" },
  { seller: "amelia_wardrobe", title: "Mango tailored blazer", description: "Single-breasted beige blazer, sharp shoulders. Dry cleaned and ready to wear.", category: "women/clothing/coats-and-jackets", brand: "Mango", size: "UK 10 / S", condition: "VERY_GOOD", colours: ["Beige"], material: "Polyester", pricePence: 2500, parcel: "MEDIUM" },
  { seller: "amelia_wardrobe", title: "Levi's 501 straight jeans", description: "Classic mid-blue wash, 501 original fit. Slight fading at the knees, which suits them.", category: "women/clothing/jeans", brand: "Levi's", size: "W28", condition: "GOOD", colours: ["Blue"], material: "Denim", pricePence: 2200, parcel: "SMALL" },
  { seller: "amelia_wardrobe", title: "& Other Stories knitted cardigan", description: "Chunky cream cardigan with tortoiseshell buttons. Very warm, small bobbles under the arms (pictured).", category: "women/clothing/jumpers-and-cardigans", brand: "& Other Stories", size: "UK 10 / S", condition: "GOOD", colours: ["Cream"], material: "Wool", pricePence: 2400, parcel: "SMALL" },
  { seller: "amelia_wardrobe", title: "Sweaty Betty Power leggings", description: "Black 7/8 leggings with pocket. No sheerness, no pilling.", category: "women/clothing/activewear", brand: "Sweaty Betty", size: "UK 8 / S", condition: "VERY_GOOD", colours: ["Black"], material: "Elastane", pricePence: 3000, parcel: "SMALL" },
  { seller: "rajsneakers", title: "Nike Air Max 90 – white/grey", description: "UK 9. Worn a handful of times, cleaned. Original box included.", category: "men/shoes/trainers", brand: "Nike", size: "UK 9", condition: "VERY_GOOD", colours: ["White", "Grey"], material: "Leather", pricePence: 6500, parcel: "MEDIUM" },
  { seller: "rajsneakers", title: "adidas Samba OG black", description: "Classic Samba in black with gum sole. UK 8.5, light creasing.", category: "men/shoes/trainers", brand: "adidas", size: "UK 8.5", condition: "GOOD", colours: ["Black"], material: "Leather", pricePence: 5000, parcel: "MEDIUM" },
  { seller: "rajsneakers", title: "New Balance 550 green", description: "White/green 550s, UK 9. Brand new, unworn, tags attached.", category: "men/shoes/trainers", brand: "New Balance", size: "UK 9", condition: "NEW_WITH_TAGS", colours: ["White", "Green"], material: "Leather", pricePence: 8000, parcel: "MEDIUM" },
  { seller: "rajsneakers", title: "Converse Chuck 70 hi navy", description: "Navy Chuck 70 high tops, UK 9. Some dirt on soles, uppers clean.", category: "men/shoes/trainers", brand: "Converse", size: "UK 9", condition: "GOOD", colours: ["Navy"], material: "Cotton", pricePence: 3200, parcel: "MEDIUM" },
  { seller: "rajsneakers", title: "Vans Old Skool black/white", description: "UK 10, barely worn – wrong size for me.", category: "men/shoes/trainers", brand: "Vans", size: "UK 10", condition: "VERY_GOOD", colours: ["Black", "White"], material: "Suede", pricePence: 2800, parcel: "MEDIUM" },
  { seller: "shiv_vintage", title: "Vintage Barbour waxed jacket", description: "Olive Beaufort-style waxed jacket, re-proofed last winter. Some honest wear on cuffs. Size M fits UK 12–14.", category: "women/clothing/coats-and-jackets", brand: "Barbour", size: "UK 14 / M", condition: "GOOD", colours: ["Khaki"], material: "Cotton", pricePence: 8500, parcel: "LARGE" },
  { seller: "shiv_vintage", title: "90s silk scarf, paisley", description: "Gorgeous burgundy and gold paisley silk scarf. 70cm square, hand-rolled edges.", category: "women/accessories/scarves", condition: "VERY_GOOD", colours: ["Burgundy", "Gold"], material: "Silk", pricePence: 1500, parcel: "SMALL" },
  { seller: "shiv_vintage", title: "Dr. Martens 1460 cherry red", description: "8-eye boots, UK 5. Broken in so no blisters! Small scuff on left toe.", category: "women/shoes/boots", brand: "Dr. Martens", size: "UK 5", condition: "GOOD", colours: ["Burgundy"], material: "Leather", pricePence: 5500, parcel: "MEDIUM" },
  { seller: "shiv_vintage", title: "Laura-style prairie dress", description: "Vintage cotton prairie dress with lace collar. No brand label; fits like a UK 10–12.", category: "women/clothing/dresses", size: "UK 12 / M", condition: "GOOD", colours: ["Cream", "Pink"], material: "Cotton", pricePence: 2600, parcel: "SMALL" },
  { seller: "shiv_vintage", title: "Radley leather crossbody bag", description: "Tan leather crossbody with Scottie dog charm. Strap adjustable. Inside is clean.", category: "women/bags/shoulder-bags", brand: "Radley", condition: "VERY_GOOD", colours: ["Brown"], material: "Leather", pricePence: 3500, parcel: "SMALL" },
  { seller: "tomf", title: "Boys' school trousers bundle x3", description: "Three pairs of grey school trousers, age 7–8. Adjustable waist. Washed and ready.", category: "kids/school-uniform", brand: "M&S", size: "7–8 years", condition: "GOOD", colours: ["Grey"], material: "Polyester", pricePence: 800, parcel: "SMALL" },
  { seller: "tomf", title: "LEGO City fire station 60320", description: "Complete with all minifigures and instructions. Built once and displayed.", category: "kids/toys-and-games", brand: "LEGO", condition: "VERY_GOOD", colours: ["Red"], material: "Plastic", pricePence: 4500, parcel: "LARGE" },
  { seller: "tomf", title: "Frugi organic dungarees 18–24m", description: "Rainbow print dungarees, organic cotton. Popper legs for nappy changes.", category: "kids/baby-clothing", brand: "Frugi", size: "18–24 months", condition: "VERY_GOOD", colours: ["Multi"], material: "Cotton", pricePence: 1200, parcel: "SMALL" },
  { seller: "tomf", title: "Clarks school shoes junior 1", description: "Black leather Velcro school shoes. Worn one term, plenty of tread left.", category: "kids/kids-shoes", brand: "Clarks", size: "Junior 1", condition: "GOOD", colours: ["Black"], material: "Leather", pricePence: 1400, parcel: "MEDIUM" },
  { seller: "tomf", title: "Jellycat Bashful Bunny medium", description: "Beige bunny, much loved but clean (machine washed on cold).", category: "kids/toys-and-games", brand: "Jellycat", condition: "GOOD", colours: ["Beige"], pricePence: 900, parcel: "SMALL" },
  { seller: "graceful_closet", title: "COS wide-leg wool trousers", description: "Charcoal wide-leg trousers, high waist. UK 12. Worn to the office a few times.", category: "women/clothing/trousers-and-leggings", brand: "COS", size: "UK 12 / M", condition: "VERY_GOOD", colours: ["Grey"], material: "Wool", pricePence: 3500, parcel: "SMALL" },
  { seller: "graceful_closet", title: "Reiss cashmere jumper", description: "Camel 100% cashmere crew neck. Hand washed only. Size M.", category: "women/clothing/jumpers-and-cardigans", brand: "Reiss", size: "UK 14 / M", condition: "VERY_GOOD", colours: ["Beige"], material: "Cashmere", pricePence: 6000, parcel: "SMALL" },
  { seller: "graceful_closet", title: "Whistles leather ankle boots", description: "Black block-heel Chelsea boots, UK 6. Resoled at the cobbler.", category: "women/shoes/boots", brand: "Whistles", size: "UK 6", condition: "GOOD", colours: ["Black"], material: "Leather", pricePence: 4200, parcel: "MEDIUM" },
  { seller: "graceful_closet", title: "Uniqlo linen shirt white", description: "Oversized white linen shirt. Perfect for summer. UK 12.", category: "women/clothing/tops-and-t-shirts", brand: "Uniqlo", size: "UK 12 / M", condition: "NEW_WITHOUT_TAGS", colours: ["White"], material: "Linen", pricePence: 1500, parcel: "SMALL" },
  { seller: "graceful_closet", title: "Mulberry Bayswater wallet", description: "Oak natural leather continental wallet with dust bag. Authentic – bought from Mulberry Regent St.", category: "women/bags/purses-and-wallets", brand: "Mulberry", condition: "VERY_GOOD", colours: ["Brown"], material: "Leather", pricePence: 18000, parcel: "SMALL" },
  { seller: "callum_reads", title: "Penguin Modern Classics bundle (6)", description: "Orwell, Woolf, Steinbeck, Camus, Huxley and Baldwin. Light shelf wear only.", category: "entertainment/books", brand: "Penguin Books", condition: "GOOD", colours: ["Multi"], material: "Paper", pricePence: 1800, parcel: "MEDIUM" },
  { seller: "callum_reads", title: "Fleetwood Mac – Rumours vinyl", description: "2011 reissue, plays perfectly. Sleeve has minor ring wear.", category: "entertainment/music/vinyl", condition: "VERY_GOOD", colours: ["Black"], pricePence: 2000, parcel: "SMALL" },
  { seller: "callum_reads", title: "Nintendo Switch OLED white", description: "Console, dock, Joy-Cons and charger. Screen protector fitted from day one. Factory reset.", category: "entertainment/video-games-and-consoles", brand: "Nintendo", condition: "VERY_GOOD", colours: ["White"], pricePence: 21000, parcel: "MEDIUM" },
  { seller: "callum_reads", title: "Catan board game complete", description: "All pieces counted and bagged. Box corners slightly worn.", category: "entertainment/board-games-and-puzzles", condition: "GOOD", colours: ["Multi"], pricePence: 1800, parcel: "MEDIUM" },
  { seller: "callum_reads", title: "Zelda: Tears of the Kingdom", description: "Switch cartridge in case. Works perfectly.", category: "entertainment/video-games-and-consoles", brand: "Nintendo", condition: "VERY_GOOD", colours: ["Multi"], pricePence: 3200, parcel: "SMALL" },
  { seller: "hannahlew", title: "Le Creuset casserole dish 24cm", description: "Volcanic orange round casserole. Some staining inside the enamel, cooks perfectly. Heavy!", category: "home/kitchen-and-dining", brand: "Le Creuset", condition: "GOOD", colours: ["Orange"], material: "Metal", pricePence: 9000, parcel: "LARGE" },
  { seller: "hannahlew", title: "Emma Bridgewater mugs x4", description: "Polka dot pint mugs, no chips or crazing.", category: "home/kitchen-and-dining", brand: "Emma Bridgewater", condition: "VERY_GOOD", colours: ["Multi"], material: "Ceramic", pricePence: 3600, parcel: "MEDIUM" },
  { seller: "hannahlew", title: "Linen duvet cover, double", description: "Stonewashed sage linen duvet cover with two pillowcases. Softer with every wash.", category: "home/bedding-and-textiles", condition: "VERY_GOOD", colours: ["Green"], material: "Linen", pricePence: 4000, parcel: "MEDIUM" },
  { seller: "hannahlew", title: "Rattan table lamp", description: "Natural rattan shade with ceramic base. UK plug, PAT tested.", category: "home/lighting", condition: "VERY_GOOD", colours: ["Beige"], material: "Wood", pricePence: 2500, parcel: "LARGE" },
  { seller: "hannahlew", title: "IKEA Fejka faux plant set", description: "Three faux plants in pots, never need watering. Collection from Cardiff also fine.", category: "home/home-decor", brand: "IKEA", condition: "VERY_GOOD", colours: ["Green"], material: "Plastic", pricePence: 1200, parcel: "MEDIUM" },
  { seller: "olliebrooks", title: "The North Face Nuptse puffer", description: "Black 1996 Retro Nuptse, size L. Down still lofty. Small repair patch on inner lining.", category: "men/clothing/coats-and-jackets", brand: "The North Face", size: "L", condition: "GOOD", colours: ["Black"], material: "Nylon", pricePence: 11000, parcel: "LARGE" },
  { seller: "olliebrooks", title: "Patagonia Better Sweater fleece", description: "Grey quarter-zip fleece, men's M. No pilling.", category: "men/clothing/jumpers-and-hoodies", brand: "Patagonia", size: "M", condition: "VERY_GOOD", colours: ["Grey"], material: "Polyester", pricePence: 5500, parcel: "SMALL" },
  { seller: "olliebrooks", title: "Carhartt WIP Detroit jacket", description: "Hamilton brown canvas with blanket lining. Size M, nicely faded.", category: "men/clothing/coats-and-jackets", brand: "Carhartt WIP", size: "M", condition: "GOOD", colours: ["Brown"], material: "Cotton", pricePence: 7500, parcel: "MEDIUM" },
  { seller: "olliebrooks", title: "Ralph Lauren Oxford shirt", description: "Light blue custom fit Oxford, size L. Collar in great shape.", category: "men/clothing/shirts", brand: "Ralph Lauren", size: "L", condition: "VERY_GOOD", colours: ["Light blue"], material: "Cotton", pricePence: 2400, parcel: "SMALL" },
  { seller: "olliebrooks", title: "Fred Perry twin tipped polo", description: "Navy with burgundy tipping, size M. Classic.", category: "men/clothing/t-shirts", brand: "Fred Perry", size: "M", condition: "VERY_GOOD", colours: ["Navy"], material: "Cotton", pricePence: 2600, parcel: "SMALL" },
  { seller: "olliebrooks", title: "Timberland 6-inch boots", description: "Wheat nubuck, UK 10. Treated with protector spray.", category: "men/shoes/boots", brand: "Timberland", size: "UK 10", condition: "GOOD", colours: ["Mustard"], material: "Suede", pricePence: 6000, parcel: "MEDIUM" },
  { seller: "bencarter", title: "Ruffwear dog harness size M", description: "Front Range harness in blue. Our dog grew out of it after a month.", category: "pets/dog-accessories", condition: "VERY_GOOD", colours: ["Blue"], material: "Nylon", pricePence: 2000, parcel: "SMALL" },
  { seller: "bencarter", title: "Large orthopaedic dog bed", description: "Grey memory-foam bed, removable washable cover. 100 x 70cm.", category: "pets/dog-accessories", condition: "GOOD", colours: ["Grey"], material: "Polyester", pricePence: 2500, parcel: "LARGE" },
  { seller: "bencarter", title: "Cat scratching post", description: "60cm sisal post with dangling toy. Our cat preferred the sofa…", category: "pets/cat-accessories", condition: "VERY_GOOD", colours: ["Beige"], material: "Wood", pricePence: 1000, parcel: "LARGE" },
  { seller: "bencarter", title: "Gymshark Apex hoodie", description: "Men's L, charcoal. Washed a few times, still crisp.", category: "men/clothing/activewear", brand: "Gymshark", size: "L", condition: "VERY_GOOD", colours: ["Grey"], material: "Cotton", pricePence: 2000, parcel: "SMALL" },
  { seller: "amelia_wardrobe", title: "Ganni seersucker check top", description: "Pink and white check, puff sleeves, tie back. UK 10.", category: "women/clothing/tops-and-t-shirts", brand: "Ganni", size: "UK 10 / S", condition: "NEW_WITH_TAGS", colours: ["Pink", "White"], material: "Cotton", pricePence: 4500, parcel: "SMALL" },
  { seller: "graceful_closet", title: "Birkenstock Arizona sandals", description: "Taupe suede, EU 39 / UK 6. Footbed moulded but lots of life left.", category: "women/shoes/sandals", brand: "Birkenstock", size: "UK 6", condition: "GOOD", colours: ["Beige"], material: "Suede", pricePence: 3500, parcel: "MEDIUM" },
  { seller: "shiv_vintage", title: "Levi's trucker denim jacket", description: "Vintage 80s Levi's trucker, mid wash. Fits UK 10–12 oversized.", category: "women/clothing/coats-and-jackets", brand: "Levi's", size: "UK 12 / M", condition: "GOOD", colours: ["Blue"], material: "Denim", pricePence: 4000, parcel: "MEDIUM" },
  { seller: "tomf", title: "Girls' party dress age 5–6", description: "Navy tulle dress with sequin bodice, worn once for a wedding.", category: "kids/girls-clothing", brand: "Monsoon", size: "5–6 years", condition: "VERY_GOOD", colours: ["Navy"], material: "Polyester", pricePence: 1500, parcel: "SMALL" },
  { seller: "callum_reads", title: "Harry Potter hardback set", description: "Bloomsbury hardbacks 1–7, mixed printings. A couple of dust jackets missing.", category: "entertainment/books", condition: "GOOD", colours: ["Multi"], material: "Paper", pricePence: 4500, parcel: "LARGE" },
];
